#!/bin/bash
HOMEDIR=/home/johmathe
#apt-get install xmonad vim xmobar xscreensaver-gl xscreensaver-data xscreensaver-data-extra xscreensaver-gl-extra
#chown -R johmathe: ${HOMEDIR}
# Logical or in case of misfortune with find.
#find ${HOMEDIR}/ -type f -exec chmod 644 {} \; || true
#find ${HOMEDIR}/ -type d -exec chmod 755 {} \; || true
