#!/bin/bash
sites_enabled="lists.arsindustrialis.org arsindustrialis.org www.arsindustrialis.org arsindustrialis.net www.arsindustrialis.net arsindustrialis.com www.arsindustrialis.com default"
sites_disabled=""
modules="userdir rewrite"
for module in $modules; do
  a2enmod $module
done
rm -f /etc/apache2/sites-enabled/*
for site in $sites_enabled; do
  a2ensite $site
done

if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi


/etc/init.d/apache2 restart
