#!/bin/bash -e
munin-node-configure --suggest --shell | sh
ln -sf /usr/share/munin/plugins/temperature_ /etc/munin/plugins/temperature_KSFO
ln -sf /usr/share/munin/plugins/sensors_ /etc/munin/plugins/sensors_temp
service munin-node restart
