#!/bin/bash
sites_enabled="defaults defaults-ssl piwik.org"
sites_disabled=""
modules="ssl rewrite"

for module in $modules; do
  a2enmod $module
done

rm -f /etc/apache2/sites-enabled/*

for site in $sites_enabled; do
  a2ensite $site
done
if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi

/etc/init.d/apache2 restart

/usr/local/bin/test-apache-cfg.sh

apt-get install -qq php5-cli
echo "edit the file /home/www/scripts/piwik-archive.sh with the token+path"

