#!/bin/bash
sites_enabled="contents.spoti.com  default  dev3.piwik.org  developer.spoti.com  stats.spoti.com  stressme.spoti.com  testing.spoti.com  video.spoti.com spoti.com www.spoti.com hyperdb.piwik.org stressme.piwik.org dev3-svn.piwik.org www.spoti.tv spoti.tv tracker.spoti.com video.spoti.tv spoti.es spoti.info adserver.spoti.tv scale-dev.piwik.org"
sites_disabled=""
modules="rewrite"

for module in $modules; do
  a2enmod $module
done
rm -f /etc/apache2/sites-enabled/*
for site in $sites_enabled; do
  a2ensite $site
done

if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi


/etc/init.d/apache2 restart
