#!/bin/bash
sites_enabled="paulinelecerf.com dsfw term films bivaudda julhirel maberetz default elias.showk  faubrysa  jlequeux	marc	slievain  term		  cfouchet		  default-ssl  gbarbaud  axelleetjulia.com johmathe	marsouil coloursofimagination.com  dlanguig     factux	    ihs  mrobache  radio    shotdetect  tcavalie projetx sensiwatt.nonutc.fr scale.piwik.org willy webmail.nonutc.fr gpiffaul.nonutc.fr alpha.nonutc.fr chantiers.nonutc.fr malamare.nonutc.fr nicleroy.nonutc.fr video.nonutc.fr ai.nonutc.fr mublog.nonutc.fr sustainable-developer.nonutc.fr sylvainlapoix.com leezic.nonutc.fr flo-et-nico.com bubbleen.com photo.nonutc.fr johmathe.name johmathe-new.nonutc.fr"
sites_disabled=""
modules="ssl rewrite dav dav_svn"
for module in $modules; do
  a2enmod $module
done
rm -f /etc/apache2/sites-enabled/*
for site in $sites_enabled; do
  a2ensite $site
done

if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi


/etc/init.d/apache2 restart
