#!/bin/bash
sites_enabled="default dev lists svn.piwik.org trac videotest.piwik.org"
sites_disabled=""
modules="ssl rewrite userdir proxy proxy_http dav dav_svn"

for module in $modules; do
  a2enmod $module
done

rm -f /etc/apache2/sites-enabled/*

for site in $sites_enabled; do
  a2ensite $site
done
if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi

/etc/init.d/apache2 restart

/usr/local/bin/test-apache-cfg.sh
