#!/bin/bash
sites_enabled="default lists tickets munin nagios backuppc"
sites_disabled=""
modules="ssl python rewrite"

rm -f /etc/apache2/sites-enabled/*

for module in $modules; do
  a2enmod $module
done

for site in $sites_enabled; do
  a2ensite $site
done

if ! apache2ctl -t; then
    echo "Apache syntax is not correct. Will not restart apache."
    exit 1
fi


/etc/init.d/apache2 restart
